version: "2.1"
services:
  sqlitebrowser:
    image: ghcr.io/linuxserver/sqlitebrowser
    container_name: sqlitebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Korea/Seoul
    volumes:
      - /Temp/db/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped